#!/usr/bin/env bash
# export_analysis.sh — Run Joern queries for all configured modules and write
# results to sdd-export/joern/ as human-readable markdown + manifest.json.
#
# Usage:
#   export_analysis.sh --config modules-config.json
#   export_analysis.sh --config modules-config.json --out sdd-export/joern
#
# Output:
#   <out>/index.md
#   <out>/manifest.json
#   <out>/modules/<name>.md   (one per module)
#   <out>/variants/<name>.md  (if variant_config is set)
#
# Requires: JOERN_HOME, python3 (stdlib only)
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
QUERY_SH="$SCRIPT_DIR/../skills/code-analysis/scripts/query.sh"
COMPARE_SH="$SCRIPT_DIR/../skills/code-analysis/scripts/compare_variants.sh"

CONFIG=""
OUT_DIR=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --config) CONFIG="$2"; shift 2 ;;
    --out)    OUT_DIR="$2"; shift 2 ;;
    *) echo "ERROR: Unknown option: $1" >&2; exit 1 ;;
  esac
done

if [[ -z "$CONFIG" ]]; then
  echo "Usage: export_analysis.sh --config modules-config.json [--out sdd-export/joern]" >&2
  exit 1
fi
if [[ ! -f "$CONFIG" ]]; then
  echo "ERROR: config file not found: $CONFIG" >&2; exit 1
fi
if [[ ! -x "$QUERY_SH" ]]; then
  echo "ERROR: query.sh not found or not executable: $QUERY_SH" >&2; exit 1
fi

# Delegate all query execution and markdown generation to Python3
python3 - "$CONFIG" "$OUT_DIR" "$QUERY_SH" "$COMPARE_SH" "$SCRIPT_DIR" <<'PYEOF'
import json, sys, os, subprocess, datetime, hashlib, shutil

config_file, out_dir_arg, query_sh, compare_sh, script_dir = sys.argv[1:]

with open(config_file) as f:
    cfg = json.load(f)

cpg_path   = cfg.get("cpg", "")
output_dir = out_dir_arg if out_dir_arg else cfg.get("output_dir", "sdd-export/joern")
modules    = cfg.get("modules", [])

# ── validate CPG ────────────────────────────────────────────────────────────
if not cpg_path or not os.path.isfile(cpg_path):
    print(f"ERROR: CPG not found: {cpg_path}\nRun harness/gen_cpg.sh first.", file=sys.stderr)
    sys.exit(2)

# ── setup output dirs ────────────────────────────────────────────────────────
for d in [output_dir,
          os.path.join(output_dir, "modules"),
          os.path.join(output_dir, "variants")]:
    os.makedirs(d, exist_ok=True)

# ── source commit info ───────────────────────────────────────────────────────
def git_head():
    try:
        r = subprocess.run(["git", "rev-parse", "--short", "HEAD"],
                           capture_output=True, text=True, cwd=os.path.dirname(config_file) or ".")
        return r.stdout.strip() or "unknown"
    except Exception:
        return "unknown"

def cpg_hash():
    h = hashlib.sha256()
    with open(cpg_path, "rb") as f:
        for chunk in iter(lambda: f.read(65536), b""):
            h.update(chunk)
    return h.hexdigest()[:16]

source_commit = git_head()
cpg_sha       = cpg_hash()
generated_at  = datetime.date.today().isoformat()

# ── query runner ─────────────────────────────────────────────────────────────
def run_query(args):
    """Run query.sh with given extra args, return parsed JSON or error dict."""
    cmd = [query_sh, "--cpg", cpg_path] + args
    r = subprocess.run(cmd, capture_output=True, text=True)
    raw = r.stdout.strip()
    if not raw:
        return {"status": "error", "error_message": f"no output (exit {r.returncode})"}
    try:
        return json.loads(raw)
    except json.JSONDecodeError:
        return {"status": "error", "error_message": f"invalid JSON: {raw[:200]}"}

# ── markdown helpers ─────────────────────────────────────────────────────────
HEADER = (
    "<!-- AUTO-GENERATED by joern-code-analysis. Do not edit manually. -->\n"
    f"<!-- generated: {generated_at} | source: {source_commit} | cpg: {cpg_sha} -->\n\n"
)

def md_callgraph(data, func_name, depth):
    result = data.get("result", {})
    if data.get("status") != "ok":
        return f"### {func_name} — 쿼리 실패\n> {data.get('error_message','')}\n\n"

    lines = [f"### {func_name} (depth={depth})\n"]
    callers = result.get("callers", [])
    callees = result.get("callees", [])

    if callers:
        lines.append("**Callers (upstream):**\n\n| 함수 | 파일 | 라인 | 깊이 |\n|------|------|------|------|\n")
        for c in callers:
            lines.append(f"| `{c['name']}` | {os.path.basename(c['file'])} | {c['line']} | {c['depth_from_target']} |\n")
    else:
        lines.append("**Callers:** 없음\n")

    lines.append("\n")
    if callees:
        lines.append("**Callees (downstream):**\n\n| 함수 | 파일 | 라인 | 깊이 |\n|------|------|------|------|\n")
        for c in callees:
            lines.append(f"| `{c['name']}` | {os.path.basename(c['file'])} | {c['line']} | {c['depth_from_target']} |\n")
    else:
        lines.append("**Callees:** 없음\n")

    if data.get("truncated"):
        lines.append("\n> ⚠️ 결과 상한에 도달. `--max-results` 증가 또는 depth 축소 권장.\n")
    lines.append("\n")
    return "".join(lines)

def md_dataflow(data, source, sink):
    result = data.get("result", {})
    if data.get("status") != "ok":
        return f"### {source} → {sink} — 쿼리 실패\n> {data.get('error_message','')}\n\n"

    reachable = result.get("reachable", False)
    icon = "✅" if reachable else "❌"
    lines = [f"### {source} → {sink}\n",
             f"- reachable: {icon}\n"]

    for p in result.get("paths", []):
        lines.append(f"- 경로 ({p['hops']} hops): `{p['summary']}`\n")

    if not result.get("paths") and reachable:
        lines.append("- 경로 상세 없음 (경로 수 상한 초과 가능성)\n")
    if data.get("truncated"):
        lines.append("> ⚠️ 경로가 잘렸습니다. `--max-results` 증가 권장.\n")
    lines.append("\n")
    return "".join(lines)

def md_env_branches(data, scope):
    result = data.get("result", {})
    if data.get("status") != "ok":
        return f"### 환경 분기 스캔 — 쿼리 실패\n> {data.get('error_message','')}\n\n"

    branches = result.get("env_sensitive_branches", [])
    if not branches:
        return f"### 환경 분기\n환경/설정 감지 분기 없음 (scope: {scope})\n\n"

    lines = ["### 환경 분기\n\n",
             "| 함수 | 파일 | 라인 | 구조 | 조건 |\n",
             "|------|------|------|------|------|\n"]
    for b in branches:
        lines.append(f"| `{b['function']}` | {os.path.basename(b['file'])} "
                     f"| {b['line']} | {b['control_structure']} | `{b['condition']}` |\n")
    if data.get("truncated"):
        lines.append("\n> ⚠️ 결과 상한 도달.\n")
    lines.append("\n")
    return "".join(lines)

def md_variants(data, cpg_a_name, cpg_b_name):
    result = data.get("result", {})
    if data.get("status") != "ok":
        return f"### Variant Diff — 쿼리 실패\n> {data.get('error_message','')}\n\n"

    lines = [f"### {cpg_a_name} vs {cpg_b_name}\n\n"]
    only_a = result.get("only_in_variant_a", [])
    only_b = result.get("only_in_variant_b", [])
    changed = result.get("changed_call_graph", [])

    lines.append(f"**요약:** {result.get('summary','')}\n\n")

    if only_a:
        lines.append(f"**{cpg_a_name} 에만 존재하는 함수:**\n")
        for fn in only_a: lines.append(f"- `{fn}`\n")
        lines.append("\n")
    if only_b:
        lines.append(f"**{cpg_b_name} 에만 존재하는 함수:**\n")
        for fn in only_b: lines.append(f"- `{fn}`\n")
        lines.append("\n")
    if changed:
        lines.append("**콜그래프가 달라진 공유 함수:**\n\n"
                     "| 함수 | B에서 추가된 호출 | B에서 제거된 호출 |\n"
                     "|------|-------------------|-------------------|\n")
        for c in changed:
            added   = ", ".join(f"`{x}`" for x in c["added_calls_in_b"])   or "—"
            removed = ", ".join(f"`{x}`" for x in c["removed_calls_in_b"]) or "—"
            lines.append(f"| `{c['function']}` | {added} | {removed} |\n")
        lines.append("\n")
    return "".join(lines)

# ── process each module ──────────────────────────────────────────────────────
manifest_modules = []
index_entries    = []

for mod in modules:
    name        = mod["name"]
    description = mod.get("description", "")
    functions   = mod.get("functions", [])
    dataflows   = mod.get("dataflows", [])
    env_scan    = mod.get("env_scan", False)
    var_cfg     = mod.get("variant_config", "")

    print(f"[{name}] 처리 중...", flush=True)
    sections = [HEADER, f"# [Joern] {name} 모듈 분석\n\n"]
    if description:
        sections.append(f"> {description}\n\n")

    queries_run = []

    # callgraph per function
    if functions:
        sections.append("## 호출 관계\n\n")
        for fn in functions:
            fname = fn["name"]
            depth = fn.get("callgraph_depth", 2)
            print(f"  callgraph: {fname} depth={depth}", flush=True)
            data = run_query(["--query", "callgraph",
                              "--target", fname, "--depth", str(depth)])
            sections.append(md_callgraph(data, fname, depth))
            queries_run.append(f"callgraph:{fname}")

    # dataflow
    if dataflows:
        sections.append("## 데이터 흐름\n\n")
        for df in dataflows:
            src, snk = df["source"], df["sink"]
            print(f"  dataflow: {src} → {snk}", flush=True)
            data = run_query(["--query", "dataflow",
                              "--source", src, "--sink", snk])
            sections.append(md_dataflow(data, src, snk))
            queries_run.append(f"dataflow:{src}→{snk}")

    # env_branches
    if env_scan:
        # scan all functions in the module scope
        target_fn = functions[0]["name"] if functions else ""
        scope_arg = ["--target", target_fn] if target_fn else []
        print(f"  env_branches (scope: {target_fn or '*'})", flush=True)
        data = run_query(["--query", "env_branches"] + scope_arg)
        sections.append("## 환경 분기\n\n")
        sections.append(md_env_branches(data, target_fn or "*"))
        queries_run.append("env_branches")

    # variant diff
    if var_cfg and os.path.isfile(var_cfg):
        try:
            with open(var_cfg) as f:
                vc = json.load(f)
            variants = vc.get("variants", [])
            if len(variants) >= 2:
                sections.append("## Variant 분석\n\n")
                # generate CPG paths from variant names
                src_dir  = os.path.dirname(cpg_path)
                for i in range(len(variants)-1):
                    va, vb = variants[i], variants[i+1]
                    cpg_a  = os.path.join(src_dir, f"cpg_{va['name']}.bin")
                    cpg_b  = os.path.join(src_dir, f"cpg_{vb['name']}.bin")
                    if os.path.isfile(cpg_a) and os.path.isfile(cpg_b):
                        print(f"  compare_variants: {va['name']} vs {vb['name']}", flush=True)
                        r = subprocess.run([compare_sh, "--cpg-a", cpg_a, "--cpg-b", cpg_b],
                                           capture_output=True, text=True)
                        try:
                            data = json.loads(r.stdout.strip())
                        except Exception:
                            data = {"status": "error",
                                    "error_message": f"parse error: {r.stdout[:200]}"}
                        sections.append(md_variants(data, va["name"], vb["name"]))
                        queries_run.append(f"compare_variants:{va['name']}↔{vb['name']}")
                    else:
                        sections.append(
                            f"### {va['name']} vs {vb['name']}\n"
                            f"> ⚠️ variant CPG 미생성. `gen_cpg.sh --variant-config {var_cfg}` 실행 필요.\n\n"
                        )
        except Exception as e:
            sections.append(f"## Variant 분석\n> ⚠️ variant-config 로드 실패: {e}\n\n")

    # write module file
    out_path = os.path.join(output_dir, "modules", f"{name}.md")
    with open(out_path, "w") as f:
        f.writelines(sections)
    print(f"  → {out_path}", flush=True)

    manifest_modules.append({
        "name": name,
        "description": description,
        "file": f"modules/{name}.md",
        "queries_run": queries_run
    })
    index_entries.append((name, description, f"modules/{name}.md"))

# ── index.md ─────────────────────────────────────────────────────────────────
index_lines = [
    HEADER,
    "# [Joern] 분석 인덱스\n\n",
    f"생성일: {generated_at}  |  소스 커밋: `{source_commit}`  |  CPG: `{cpg_sha}`\n\n",
    "| 모듈 | 설명 | 분석 파일 |\n",
    "|------|------|----------|\n",
]
for name, desc, path in index_entries:
    index_lines.append(f"| [{name}]({path}) | {desc} | [link]({path}) |\n")

with open(os.path.join(output_dir, "index.md"), "w") as f:
    f.writelines(index_lines)

# ── manifest.json ─────────────────────────────────────────────────────────────
manifest = {
    "generated": generated_at,
    "source_commit": source_commit,
    "cpg_path": cpg_path,
    "cpg_sha256": cpg_sha,
    "modules": manifest_modules
}
with open(os.path.join(output_dir, "manifest.json"), "w") as f:
    json.dump(manifest, f, indent=2, ensure_ascii=False)

print(f"\n완료: {output_dir}/")
print(f"  index.md, manifest.json, {len(manifest_modules)}개 모듈 파일")
PYEOF
